name: CI-Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: 'true'
      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Test Build
        run: |
          chmod +x ./gradlew
          ./gradlew :module:assembleRelease
      - name: Get Module Version
        id: module-version
        run: |
          MODULE_VERSION=$(cat module.gradle | grep "moduleVersion =" | awk -F'"' '{print $2}')
          echo "version=$MODULE_VERSION" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v3
        with:
          name: ZygiskFrida-${{ steps.module-version.outputs.version }}-release
          path: out/magisk_module_zygisk_release
      - uses: actions/upload-artifact@v3
        with:
          name: ZygiskFrida-${{ steps.module-version.outputs.version }}-riru-release
          path: out/magisk_module_riru_release
